### ISSUE TITLE
Can I please have  anew Security controls example document

### ISSUE THREAD

**Issue by wglennie** [co-cddo/SbD#4]
<TEST> We need to add a document covering a super new NIST version2 mega secure controls set

**Comment by DejiSBD** [comment]
Please can you provide some more information.

**Comment by wglennie** [comment]
This is all test and probably not needed

**Comment by DejiSBD** [comment]
All information required. Assigning for creation.

**Comment by DejiSBD** [comment]
@wglennie do you have any comments or insights?

**Comment by DejiSBD** [comment]
Assigning to @wglennie for creation

**Comment by DejiSBD** [comment]
Completed

**Comment by DejiSBD** [comment]
close
